import type { ConversationStage } from "../shared/constants";
import { CONVERSATION_STAGES } from "../shared/constants";

const ACTIVE_STAGES: readonly ConversationStage[] = [
  CONVERSATION_STAGES.INITIALIZED,
  CONVERSATION_STAGES.INTAKE,
  CONVERSATION_STAGES.CLARIFICATION,
  CONVERSATION_STAGES.CONFIRMATION,
];

const ALLOWED_TRANSITIONS: Readonly<
  Record<ConversationStage, readonly ConversationStage[]>
> = {
  [CONVERSATION_STAGES.INITIALIZED]: [
    CONVERSATION_STAGES.INTAKE,
    CONVERSATION_STAGES.ESCALATION,
    CONVERSATION_STAGES.ABANDONED,
  ],
  [CONVERSATION_STAGES.INTAKE]: [
    CONVERSATION_STAGES.CLARIFICATION,
    CONVERSATION_STAGES.CONFIRMATION,
    CONVERSATION_STAGES.ESCALATION,
    CONVERSATION_STAGES.ABANDONED,
  ],
  [CONVERSATION_STAGES.CLARIFICATION]: [
    CONVERSATION_STAGES.INTAKE,
    CONVERSATION_STAGES.CONFIRMATION,
    CONVERSATION_STAGES.ESCALATION,
    CONVERSATION_STAGES.ABANDONED,
  ],
  [CONVERSATION_STAGES.CONFIRMATION]: [
    CONVERSATION_STAGES.INTAKE,
    CONVERSATION_STAGES.CLARIFICATION,
    CONVERSATION_STAGES.HANDOFF,
    CONVERSATION_STAGES.ESCALATION,
    CONVERSATION_STAGES.ABANDONED,
  ],
  [CONVERSATION_STAGES.ESCALATION]: [
    CONVERSATION_STAGES.HANDOFF,
    CONVERSATION_STAGES.ABANDONED,
  ],
  [CONVERSATION_STAGES.HANDOFF]: [CONVERSATION_STAGES.COMPLETED],
  [CONVERSATION_STAGES.COMPLETED]: [],
  [CONVERSATION_STAGES.ABANDONED]: [],
};

export function canTransitionStage(
  current: ConversationStage,
  next: ConversationStage,
): boolean {
  return ALLOWED_TRANSITIONS[current].includes(next);
}

export function isActiveStage(stage: ConversationStage): boolean {
  return ACTIVE_STAGES.includes(stage);
}
